name: postgres-example
channels:
  - defaults
dependencies:
  - ipython-sql
  - pandas
  - postgresql
  - psycopg2
  - pip:
    - git+https://github.com/jupyterlab/jupyterlab
    - https://github.com/jupyterhub/jupyter-server-proxy/archive/master.zip
