name: postgres-example
channels:
  - defaults
dependencies:
  - postgresql
  - psycopg2
  - yarn
  - pip:
    - jupyter-server-proxy
    - pandas
    - git+https://github.com/catherinedevlin/ipython-sql.git
