name: postgres-example
channels:
  - defaults
dependencies:
  - gunicorn
  - ipython-sql
  - pandas
  - postgresql
  - psycopg2
  - pip:
    - git+https://github.com/jupyterlab/jupyterlab
    - https://github.com/jupyterhub/jupyter-server-proxy/archive/master.zip
    - https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v4.1/pip/pgadmin4-4.1-py2.py3-none-any.whl
