name: postgres-example
channels:
  - defaults
dependencies:
  - postgresql
  - psycopg2
  - yarn
  - pip:
    - https://github.com/jupyterhub/jupyter-server-proxy/archive/master.zip
    - pandas
    - git+https://github.com/catherinedevlin/ipython-sql.git
